<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>Private package to test Cube.* projects.</Description>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <RootNamespace>Cube.Tests</RootNamespace>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\Libraries\Cube.Core\Cube.Core.csproj" />
        <ProjectReference Include="..\..\Libraries\Cube.Logging\Cube.Logging.csproj" />
        <PackageReference Include="NUnit" Version="4.6.1" />
    </ItemGroup>
</Project>
