<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>Wraps the SuperLightLogger package compatible with the Cube.ILoggerSource interface.</Description>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Cube.Core\Cube.Core.csproj" />
        <PackageReference Include="SuperLightLogger" Version="1.0.9" />
    </ItemGroup>
</Project>
