//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;
namespace Cube.FileSystem.SevenZip.Ice.Properties {


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {

        private static ResourceManager resourceMan;

        private static CultureInfo resourceCulture;

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Cube.FileSystem.SevenZip.Ice.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 7-Zip.
        /// </summary>
        internal static string Ctx7z {
            get {
                return ResourceManager.GetString("Ctx7z", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 圧縮.
        /// </summary>
        internal static string CtxArchive {
            get {
                return ResourceManager.GetString("CtxArchive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BZip2.
        /// </summary>
        internal static string CtxBz2 {
            get {
                return ResourceManager.GetString("CtxBz2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to デスクトップに解凍.
        /// </summary>
        internal static string CtxDesktop {
            get {
                return ResourceManager.GetString("CtxDesktop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 詳細設定.
        /// </summary>
        internal static string CtxDetails {
            get {
                return ResourceManager.GetString("CtxDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 解凍.
        /// </summary>
        internal static string CtxExtract {
            get {
                return ResourceManager.GetString("CtxExtract", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GZip.
        /// </summary>
        internal static string CtxGz {
            get {
                return ResourceManager.GetString("CtxGz", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 圧縮してメール送信.
        /// </summary>
        internal static string CtxMail {
            get {
                return ResourceManager.GetString("CtxMail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ドキュメントに解凍.
        /// </summary>
        internal static string CtxMyDocuments {
            get {
                return ResourceManager.GetString("CtxMyDocuments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 場所を指定して解凍.
        /// </summary>
        internal static string CtxQuery {
            get {
                return ResourceManager.GetString("CtxQuery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 自己解凍形式.
        /// </summary>
        internal static string CtxSfx {
            get {
                return ResourceManager.GetString("CtxSfx", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ここに解凍.
        /// </summary>
        internal static string CtxSource {
            get {
                return ResourceManager.GetString("CtxSource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Xz.
        /// </summary>
        internal static string CtxXz {
            get {
                return ResourceManager.GetString("CtxXz", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        internal static string CtxZip {
            get {
                return ResourceManager.GetString("CtxZip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zip (パスワード).
        /// </summary>
        internal static string CtxZipPassword {
            get {
                return ResourceManager.GetString("CtxZipPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CubeICE 圧縮.
        /// </summary>
        internal static string ScArcive {
            get {
                return ResourceManager.GetString("ScArcive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CubeICE 解凍.
        /// </summary>
        internal static string ScExtract {
            get {
                return ResourceManager.GetString("ScExtract", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CubeICE 設定.
        /// </summary>
        internal static string ScSettings {
            get {
                return ResourceManager.GetString("ScSettings", resourceCulture);
            }
        }
    }
}
